/* Repositories */
export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START';
export const FETCH_REPOSITORIES_ERROR = 'FETCH_REPOSITORIES_ERROR';
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';

/* Repository */
export const FETCH_REPOSITORY_START = 'FETCH_REPOSITORY_START';
export const FETCH_REPOSITORY_ERROR = 'FETCH_REPOSITORY_ERROR';
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS';

/* Owner */
export const FETCH_OWNER_START = 'FETCH_OWNER_START';
export const FETCH_OWNER_ERROR = 'FETCH_OWNER_ERROR';
export const FETCH_OWNER_SUCCESS = 'FETCH_OWNER_SUCCESS';
